name: nex_event_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  another_flutter_splash_screen: ^1.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.5
  http: ^1.2.2
  file_picker: ^8.1.4
  email_auth: ^2.0.0
  mailer: ^6.2.0
  salomon_bottom_bar: ^3.3.2
  bcrypt: ^1.1.3
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  multi_select_flutter: ^4.1.3
  intl: ^0.19.0
  url_launcher: ^6.1.8
  marquee: ^2.3.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.4


dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/nexaevent.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans_10pt-Black.ttf
        - asset: fonts/NunitoSans_10pt-Regular.ttf
        - asset: fonts/NunitoSans_10pt-Bold.ttf
