// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'firebase_options.dart';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxkaTlS9iDXHBfkTls9PQpuISp4nn_Z5U',
    appId: '1:350350146473:web:af614b510922e6f5ef22b8',
    messagingSenderId: '350350146473',
    projectId: 'nexevent-95ef9',
    authDomain: 'nexevent-95ef9.firebaseapp.com',
    storageBucket: 'nexevent-95ef9.firebasestorage.app',
    measurementId: 'G-JHTNXYFSKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ_J79IIzbNDCSMEDvDFM4k7sUzhW4OGc',
    appId: '1:350350146473:android:abdb4cb7350b16ceef22b8',
    messagingSenderId: '350350146473',
    projectId: 'nexevent-95ef9',
    storageBucket: 'nexevent-95ef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP2Tk5NcaxRdWgPZNlcE4eTkyBkkd8IqY',
    appId: '1:350350146473:ios:2553a68ddbc0aebbef22b8',
    messagingSenderId: '350350146473',
    projectId: 'nexevent-95ef9',
    storageBucket: 'nexevent-95ef9.firebasestorage.app',
    iosBundleId: 'com.example.nexEventApp',
  );

}